// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ActionRequestMagician
    {
        [DataMember(Name = "state")]
        public MagicianState State;
        [DataMember(Name = "attack_information")]
        public AttackInformation AttackInformation;
        [DataMember(Name = "reload_information")]
        public ReloadInformation ReloadInformation;
        [DataMember(Name = "dust_information")]
        public DustInformation DustInformation;

        public ActionRequestMagician(
            MagicianState State,
            AttackInformation AttackInformation,
            ReloadInformation ReloadInformation,
            DustInformation DustInformation
        )
        {
            this.State = State;
            this.AttackInformation = AttackInformation;
            this.ReloadInformation = ReloadInformation;
            this.DustInformation = DustInformation;
        }

        public ActionRequestMagician()
        {
            this.AttackInformation = new();
            this.ReloadInformation = new();
            this.DustInformation = new();
        }
    }
}
