// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ApplicationInformation
    {
        [DataMember(Name = "application_type")]
        public ApplicationType ApplicationType;
        [DataMember(Name = "current_time")]
        public float? CurrentTime;
        [DataMember(Name = "end_time")]
        public float? EndTime;
        [DataMember(Name = "reapply_time")]
        public float? ReapplyTime;
        [DataMember(Name = "current_reapply_time")]
        public float? CurrentReapplyTime;
        [DataMember(Name = "applied")]
        public bool? Applied;

        public ApplicationInformation(
            ApplicationType ApplicationType,
            float? CurrentTime,
            float? EndTime,
            float? ReapplyTime,
            float? CurrentReapplyTime,
            bool? Applied
        )
        {
            this.ApplicationType = ApplicationType;
            this.CurrentTime = CurrentTime;
            this.EndTime = EndTime;
            this.ReapplyTime = ReapplyTime;
            this.CurrentReapplyTime = CurrentReapplyTime;
            this.Applied = Applied;
        }

        public ApplicationInformation()
        {
        }
    }
}
