// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AttackInformation
    {
        [DataMember(Name = "CameraPositionOffset")]
        public DbVector3 CameraPositionOffset;
        [DataMember(Name = "CameraYawOffset")]
        public float CameraYawOffset;
        [DataMember(Name = "CameraPitchOffset")]
        public float CameraPitchOffset;
        [DataMember(Name = "SpawnPointOffset")]
        public DbVector3 SpawnPointOffset;
        [DataMember(Name = "MaxDistance")]
        public float MaxDistance;

        public AttackInformation(
            DbVector3 CameraPositionOffset,
            float CameraYawOffset,
            float CameraPitchOffset,
            DbVector3 SpawnPointOffset,
            float MaxDistance
        )
        {
            this.CameraPositionOffset = CameraPositionOffset;
            this.CameraYawOffset = CameraYawOffset;
            this.CameraPitchOffset = CameraPitchOffset;
            this.SpawnPointOffset = SpawnPointOffset;
            this.MaxDistance = MaxDistance;
        }

        public AttackInformation()
        {
            this.CameraPositionOffset = new();
            this.SpawnPointOffset = new();
        }
    }
}
