// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CapsuleCollider
    {
        [DataMember(Name = "Center")]
        public DbVector3 Center;
        [DataMember(Name = "HeightEndToEnd")]
        public float HeightEndToEnd;
        [DataMember(Name = "Radius")]
        public float Radius;
        [DataMember(Name = "Direction")]
        public DbVector3 Direction;

        public CapsuleCollider(
            DbVector3 Center,
            float HeightEndToEnd,
            float Radius,
            DbVector3 Direction
        )
        {
            this.Center = Center;
            this.HeightEndToEnd = HeightEndToEnd;
            this.Radius = Radius;
            this.Direction = Direction;
        }

        public CapsuleCollider()
        {
            this.Center = new();
            this.Direction = new();
        }
    }
}
