// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CollisionEntry
    {
        [DataMember(Name = "entry_type")]
        public CollisionEntryType EntryType;
        [DataMember(Name = "id")]
        public ulong Id;

        public CollisionEntry(
            CollisionEntryType EntryType,
            ulong Id
        )
        {
            this.EntryType = EntryType;
            this.Id = Id;
        }

        public CollisionEntry()
        {
        }
    }
}
