// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CollisionEntry
    {
        [DataMember(Name = "Type")]
        public CollisionEntryType Type;
        [DataMember(Name = "Id")]
        public uint Id;

        public CollisionEntry(
            CollisionEntryType Type,
            uint Id
        )
        {
            this.Type = Type;
            this.Id = Id;
        }

        public CollisionEntry()
        {
        }
    }
}
