// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CombatInformation
    {
        [DataMember(Name = "health")]
        public float Health;
        [DataMember(Name = "max_health")]
        public float MaxHealth;
        [DataMember(Name = "speed_multiplier")]
        public float SpeedMultiplier;
        [DataMember(Name = "game_score")]
        public uint GameScore;

        public CombatInformation(
            float Health,
            float MaxHealth,
            float SpeedMultiplier,
            uint GameScore
        )
        {
            this.Health = Health;
            this.MaxHealth = MaxHealth;
            this.SpeedMultiplier = SpeedMultiplier;
            this.GameScore = GameScore;
        }

        public CombatInformation()
        {
        }
    }
}
