// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CombatInformation
    {
        [DataMember(Name = "health")]
        public float Health;
        [DataMember(Name = "max_health")]
        public float MaxHealth;
        [DataMember(Name = "speed_multiplier")]
        public float SpeedMultiplier;
        [DataMember(Name = "game_score")]
        public uint GameScore;
        [DataMember(Name = "blind")]
        public bool Blind;
        [DataMember(Name = "reversed")]
        public bool Reversed;
        [DataMember(Name = "stunned")]
        public bool Stunned;
        [DataMember(Name = "cloaked")]
        public bool Cloaked;
        [DataMember(Name = "hypnosis")]
        public bool Hypnosis;

        public CombatInformation(
            float Health,
            float MaxHealth,
            float SpeedMultiplier,
            uint GameScore,
            bool Blind,
            bool Reversed,
            bool Stunned,
            bool Cloaked,
            bool Hypnosis
        )
        {
            this.Health = Health;
            this.MaxHealth = MaxHealth;
            this.SpeedMultiplier = SpeedMultiplier;
            this.GameScore = GameScore;
            this.Blind = Blind;
            this.Reversed = Reversed;
            this.Stunned = Stunned;
            this.Cloaked = Cloaked;
            this.Hypnosis = Hypnosis;
        }

        public CombatInformation()
        {
        }
    }
}
