// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ComplexCollider
    {
        [DataMember(Name = "ConvexHulls")]
        public System.Collections.Generic.List<ConvexHullCollider> ConvexHulls;
        [DataMember(Name = "CenterPoint")]
        public DbVector3 CenterPoint;

        public ComplexCollider(
            System.Collections.Generic.List<ConvexHullCollider> ConvexHulls,
            DbVector3 CenterPoint
        )
        {
            this.ConvexHulls = ConvexHulls;
            this.CenterPoint = CenterPoint;
        }

        public ComplexCollider()
        {
            this.ConvexHulls = new();
            this.CenterPoint = new();
        }
    }
}
