// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConvexHullCollider
    {
        [DataMember(Name = "VerticesLocal")]
        public System.Collections.Generic.List<DbVector3> VerticesLocal;
        [DataMember(Name = "TriangleIndicesLocal")]
        public System.Collections.Generic.List<int> TriangleIndicesLocal;
        [DataMember(Name = "Margin")]
        public float Margin;

        public ConvexHullCollider(
            System.Collections.Generic.List<DbVector3> VerticesLocal,
            System.Collections.Generic.List<int> TriangleIndicesLocal,
            float Margin
        )
        {
            this.VerticesLocal = VerticesLocal;
            this.TriangleIndicesLocal = TriangleIndicesLocal;
            this.Margin = Margin;
        }

        public ConvexHullCollider()
        {
            this.VerticesLocal = new();
            this.TriangleIndicesLocal = new();
        }
    }
}
