// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DamageInformation
    {
        [DataMember(Name = "base_damage")]
        public float BaseDamage;
        [DataMember(Name = "damage_multiplier")]
        public float DamageMultiplier;

        public DamageInformation(
            float BaseDamage,
            float DamageMultiplier
        )
        {
            this.BaseDamage = BaseDamage;
            this.DamageMultiplier = DamageMultiplier;
        }

        public DamageInformation()
        {
        }
    }
}
