// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DbRotation2
    {
        [DataMember(Name = "yaw")]
        public float Yaw;
        [DataMember(Name = "pitch")]
        public float Pitch;

        public DbRotation2(
            float Yaw,
            float Pitch
        )
        {
            this.Yaw = Yaw;
            this.Pitch = Pitch;
        }

        public DbRotation2()
        {
        }
    }
}
