// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DbRotation2
    {
        [DataMember(Name = "Yaw")]
        public float Yaw;
        [DataMember(Name = "Pitch")]
        public float Pitch;

        public DbRotation2(
            float Yaw,
            float Pitch
        )
        {
            this.Yaw = Yaw;
            this.Pitch = Pitch;
        }

        public DbRotation2()
        {
        }
    }
}
