// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Effect
    {
        [DataMember(Name = "Type")]
        public EffectType Type;

        public Effect(EffectType Type)
        {
            this.Type = Type;
        }

        public Effect()
        {
        }
    }
}
