// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Effect
    {
        [DataMember(Name = "effect_type")]
        public EffectType EffectType;
        [DataMember(Name = "application_information")]
        public ApplicationInformation ApplicationInformation;
        [DataMember(Name = "damage_information")]
        public DamageEffectInformation? DamageInformation;
        [DataMember(Name = "cloak_information")]
        public CloakEffectInformation? CloakInformation;
        [DataMember(Name = "dust_information")]
        public DustEffectInformation? DustInformation;
        [DataMember(Name = "speed_information")]
        public SpeedEffectInformation? SpeedInformation;
        [DataMember(Name = "hypnosis_information")]
        public HypnosisEffectInformation? HypnosisInformation;
        [DataMember(Name = "stunned_information")]
        public StunnedEffectInformation? StunnedInformation;
        [DataMember(Name = "tarot_information")]
        public TarotEffectInformation? TarotInformation;

        public Effect(
            EffectType EffectType,
            ApplicationInformation ApplicationInformation,
            DamageEffectInformation? DamageInformation,
            CloakEffectInformation? CloakInformation,
            DustEffectInformation? DustInformation,
            SpeedEffectInformation? SpeedInformation,
            HypnosisEffectInformation? HypnosisInformation,
            StunnedEffectInformation? StunnedInformation,
            TarotEffectInformation? TarotInformation
        )
        {
            this.EffectType = EffectType;
            this.ApplicationInformation = ApplicationInformation;
            this.DamageInformation = DamageInformation;
            this.CloakInformation = CloakInformation;
            this.DustInformation = DustInformation;
            this.SpeedInformation = SpeedInformation;
            this.HypnosisInformation = HypnosisInformation;
            this.StunnedInformation = StunnedInformation;
            this.TarotInformation = TarotInformation;
        }

        public Effect()
        {
            this.ApplicationInformation = new();
        }
    }
}
