// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Game
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "max_players")]
        public uint MaxPlayers;
        [DataMember(Name = "current_players")]
        public uint CurrentPlayers;
        [DataMember(Name = "in_progress")]
        public bool InProgress;

        public Game(
            uint Id,
            uint MaxPlayers,
            uint CurrentPlayers,
            bool InProgress
        )
        {
            this.Id = Id;
            this.MaxPlayers = MaxPlayers;
            this.CurrentPlayers = CurrentPlayers;
            this.InProgress = InProgress;
        }

        public Game()
        {
        }
    }
}
