// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class HandleMagicianTimersTimer
    {
        [DataMember(Name = "scheduled_id")]
        public ulong ScheduledId;
        [DataMember(Name = "scheduled_at")]
        public SpacetimeDB.ScheduleAt ScheduledAt;
        [DataMember(Name = "tick_rate")]
        public float TickRate;
        [DataMember(Name = "MatchId")]
        public uint MatchId;

        public HandleMagicianTimersTimer(
            ulong ScheduledId,
            SpacetimeDB.ScheduleAt ScheduledAt,
            float TickRate,
            uint MatchId
        )
        {
            this.ScheduledId = ScheduledId;
            this.ScheduledAt = ScheduledAt;
            this.TickRate = TickRate;
            this.MatchId = MatchId;
        }

        public HandleMagicianTimersTimer()
        {
            this.ScheduledAt = null!;
        }
    }
}
