// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class HypnosisEffectInformation
    {
        [DataMember(Name = "last_target_id")]
        public ulong? LastTargetId;

        public HypnosisEffectInformation(ulong? LastTargetId)
        {
            this.LastTargetId = LastTargetId;
        }

        public HypnosisEffectInformation()
        {
        }
    }
}
