// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class HypnosisCameraInformation
    {
        [DataMember(Name = "camera_position_offset")]
        public DbVector3 CameraPositionOffset;
        [DataMember(Name = "camera_yaw_offset")]
        public float CameraYawOffset;
        [DataMember(Name = "camera_pitch_offset")]
        public float CameraPitchOffset;
        [DataMember(Name = "spawn_point_offset")]
        public DbVector3 SpawnPointOffset;
        [DataMember(Name = "max_distance")]
        public float MaxDistance;

        public HypnosisCameraInformation(
            DbVector3 CameraPositionOffset,
            float CameraYawOffset,
            float CameraPitchOffset,
            DbVector3 SpawnPointOffset,
            float MaxDistance
        )
        {
            this.CameraPositionOffset = CameraPositionOffset;
            this.CameraYawOffset = CameraYawOffset;
            this.CameraPitchOffset = CameraPitchOffset;
            this.SpawnPointOffset = SpawnPointOffset;
            this.MaxDistance = MaxDistance;
        }

        public HypnosisCameraInformation()
        {
            this.CameraPositionOffset = new();
            this.SpawnPointOffset = new();
        }
    }
}
