// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class KinematicInformation
    {
        [DataMember(Name = "jump")]
        public bool Jump;
        [DataMember(Name = "falling")]
        public bool Falling;
        [DataMember(Name = "crouched")]
        public bool Crouched;
        [DataMember(Name = "grounded")]
        public bool Grounded;
        [DataMember(Name = "sprinting")]
        public bool Sprinting;

        public KinematicInformation(
            bool Jump,
            bool Falling,
            bool Crouched,
            bool Grounded,
            bool Sprinting
        )
        {
            this.Jump = Jump;
            this.Falling = Falling;
            this.Crouched = Crouched;
            this.Grounded = Grounded;
            this.Sprinting = Sprinting;
        }

        public KinematicInformation()
        {
        }
    }
}
