// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class KinematicInformation
    {
        [DataMember(Name = "Falling")]
        public bool Falling;
        [DataMember(Name = "Crouched")]
        public bool Crouched;
        [DataMember(Name = "Grounded")]
        public bool Grounded;
        [DataMember(Name = "Landing")]
        public bool Landing;
        [DataMember(Name = "Sprinting")]
        public bool Sprinting;

        public KinematicInformation(
            bool Falling,
            bool Crouched,
            bool Grounded,
            bool Landing,
            bool Sprinting
        )
        {
            this.Falling = Falling;
            this.Crouched = Crouched;
            this.Grounded = Grounded;
            this.Landing = Landing;
            this.Sprinting = Sprinting;
        }

        public KinematicInformation()
        {
        }
    }
}
