// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Magician
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "Id")]
        public uint Id;
        [DataMember(Name = "Name")]
        public string Name;
        [DataMember(Name = "MatchId")]
        public uint MatchId;
        [DataMember(Name = "Position")]
        public DbVector3 Position;
        [DataMember(Name = "Rotation")]
        public DbRotation2 Rotation;
        [DataMember(Name = "Velocity")]
        public DbVector3 Velocity;
        [DataMember(Name = "CorrectedVelocity")]
        public DbVector3 CorrectedVelocity;
        [DataMember(Name = "Collider")]
        public ComplexCollider Collider;
        [DataMember(Name = "CollisionEntries")]
        public System.Collections.Generic.List<CollisionEntry> CollisionEntries;
        [DataMember(Name = "IsColliding")]
        public bool IsColliding;
        [DataMember(Name = "State")]
        public MagicianState State;
        [DataMember(Name = "KinematicInformation")]
        public KinematicInformation KinematicInformation;
        [DataMember(Name = "PlayerPermissionConfig")]
        public System.Collections.Generic.List<PermissionEntry> PlayerPermissionConfig;
        [DataMember(Name = "Timers")]
        public System.Collections.Generic.List<Timer> Timers;
        [DataMember(Name = "Bullets")]
        public System.Collections.Generic.List<ThrowingCard> Bullets;
        [DataMember(Name = "BulletCapacity")]
        public int BulletCapacity;

        public Magician(
            SpacetimeDB.Identity Identity,
            uint Id,
            string Name,
            uint MatchId,
            DbVector3 Position,
            DbRotation2 Rotation,
            DbVector3 Velocity,
            DbVector3 CorrectedVelocity,
            ComplexCollider Collider,
            System.Collections.Generic.List<CollisionEntry> CollisionEntries,
            bool IsColliding,
            MagicianState State,
            KinematicInformation KinematicInformation,
            System.Collections.Generic.List<PermissionEntry> PlayerPermissionConfig,
            System.Collections.Generic.List<Timer> Timers,
            System.Collections.Generic.List<ThrowingCard> Bullets,
            int BulletCapacity
        )
        {
            this.Identity = Identity;
            this.Id = Id;
            this.Name = Name;
            this.MatchId = MatchId;
            this.Position = Position;
            this.Rotation = Rotation;
            this.Velocity = Velocity;
            this.CorrectedVelocity = CorrectedVelocity;
            this.Collider = Collider;
            this.CollisionEntries = CollisionEntries;
            this.IsColliding = IsColliding;
            this.State = State;
            this.KinematicInformation = KinematicInformation;
            this.PlayerPermissionConfig = PlayerPermissionConfig;
            this.Timers = Timers;
            this.Bullets = Bullets;
            this.BulletCapacity = BulletCapacity;
        }

        public Magician()
        {
            this.Name = "";
            this.Position = new();
            this.Rotation = new();
            this.Velocity = new();
            this.CorrectedVelocity = new();
            this.Collider = new();
            this.CollisionEntries = new();
            this.KinematicInformation = new();
            this.PlayerPermissionConfig = new();
            this.Timers = new();
            this.Bullets = new();
        }
    }
}
