// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Magician
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "game_id")]
        public uint GameId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "rotation")]
        public DbRotation2 Rotation;
        [DataMember(Name = "velocity")]
        public DbVector3 Velocity;
        [DataMember(Name = "corrected_velocity")]
        public DbVector3 CorrectedVelocity;
        [DataMember(Name = "collider")]
        public ComplexCollider Collider;
        [DataMember(Name = "collision_entries")]
        public System.Collections.Generic.List<CollisionEntry> CollisionEntries;
        [DataMember(Name = "is_colliding")]
        public bool IsColliding;
        [DataMember(Name = "state")]
        public MagicianState State;
        [DataMember(Name = "kinematic_information")]
        public KinematicInformation KinematicInformation;
        [DataMember(Name = "permissions")]
        public System.Collections.Generic.List<PermissionEntry> Permissions;
        [DataMember(Name = "timers")]
        public System.Collections.Generic.List<Timer> Timers;
        [DataMember(Name = "bullets")]
        public System.Collections.Generic.List<ThrowingCard> Bullets;
        [DataMember(Name = "bullet_capacity")]
        public int BulletCapacity;
        [DataMember(Name = "effects")]
        public System.Collections.Generic.List<Effect> Effects;

        public Magician(
            SpacetimeDB.Identity Identity,
            ulong Id,
            uint GameId,
            string Name,
            DbVector3 Position,
            DbRotation2 Rotation,
            DbVector3 Velocity,
            DbVector3 CorrectedVelocity,
            ComplexCollider Collider,
            System.Collections.Generic.List<CollisionEntry> CollisionEntries,
            bool IsColliding,
            MagicianState State,
            KinematicInformation KinematicInformation,
            System.Collections.Generic.List<PermissionEntry> Permissions,
            System.Collections.Generic.List<Timer> Timers,
            System.Collections.Generic.List<ThrowingCard> Bullets,
            int BulletCapacity,
            System.Collections.Generic.List<Effect> Effects
        )
        {
            this.Identity = Identity;
            this.Id = Id;
            this.GameId = GameId;
            this.Name = Name;
            this.Position = Position;
            this.Rotation = Rotation;
            this.Velocity = Velocity;
            this.CorrectedVelocity = CorrectedVelocity;
            this.Collider = Collider;
            this.CollisionEntries = CollisionEntries;
            this.IsColliding = IsColliding;
            this.State = State;
            this.KinematicInformation = KinematicInformation;
            this.Permissions = Permissions;
            this.Timers = Timers;
            this.Bullets = Bullets;
            this.BulletCapacity = BulletCapacity;
            this.Effects = Effects;
        }

        public Magician()
        {
            this.Name = "";
            this.Position = new();
            this.Rotation = new();
            this.Velocity = new();
            this.CorrectedVelocity = new();
            this.Collider = new();
            this.CollisionEntries = new();
            this.KinematicInformation = new();
            this.Permissions = new();
            this.Timers = new();
            this.Bullets = new();
            this.Effects = new();
        }
    }
}
