// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Map
    {
        [DataMember(Name = "Id")]
        public uint Id;
        [DataMember(Name = "Name")]
        public string Name;
        [DataMember(Name = "Collider")]
        public ComplexCollider Collider;

        public Map(
            uint Id,
            string Name,
            ComplexCollider Collider
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.Collider = Collider;
        }

        public Map()
        {
            this.Name = "";
            this.Collider = new();
        }
    }
}
