// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Map
    {
        [DataMember(Name = "Id")]
        public uint Id;
        [DataMember(Name = "Name")]
        public string Name;
        [DataMember(Name = "GjkCollider")]
        public ComplexCollider GjkCollider;

        public Map(
            uint Id,
            string Name,
            ComplexCollider GjkCollider
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.GjkCollider = GjkCollider;
        }

        public Map()
        {
            this.Name = "";
            this.GjkCollider = new();
        }
    }
}
