// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MovementRequest
    {
        [DataMember(Name = "MoveForward")]
        public bool MoveForward;
        [DataMember(Name = "MoveBackward")]
        public bool MoveBackward;
        [DataMember(Name = "MoveLeft")]
        public bool MoveLeft;
        [DataMember(Name = "MoveRight")]
        public bool MoveRight;
        [DataMember(Name = "Sprint")]
        public bool Sprint;
        [DataMember(Name = "Jump")]
        public bool Jump;
        [DataMember(Name = "Crouch")]
        public bool Crouch;
        [DataMember(Name = "Aim")]
        public DbRotation2 Aim;

        public MovementRequest(
            bool MoveForward,
            bool MoveBackward,
            bool MoveLeft,
            bool MoveRight,
            bool Sprint,
            bool Jump,
            bool Crouch,
            DbRotation2 Aim
        )
        {
            this.MoveForward = MoveForward;
            this.MoveBackward = MoveBackward;
            this.MoveLeft = MoveLeft;
            this.MoveRight = MoveRight;
            this.Sprint = Sprint;
            this.Jump = Jump;
            this.Crouch = Crouch;
            this.Aim = Aim;
        }

        public MovementRequest()
        {
            this.Aim = new();
        }
    }
}
