// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MovementRequest
    {
        [DataMember(Name = "Velocity")]
        public DbVector3 Velocity;
        [DataMember(Name = "Sprint")]
        public bool Sprint;
        [DataMember(Name = "Jump")]
        public bool Jump;
        [DataMember(Name = "Aim")]
        public DbRotation2 Aim;

        public MovementRequest(
            DbVector3 Velocity,
            bool Sprint,
            bool Jump,
            DbRotation2 Aim
        )
        {
            this.Velocity = Velocity;
            this.Sprint = Sprint;
            this.Jump = Jump;
            this.Aim = Aim;
        }

        public MovementRequest()
        {
            this.Velocity = new();
            this.Aim = new();
        }
    }
}
