// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PermissionEntry
    {
        [DataMember(Name = "Key")]
        public string Key;
        [DataMember(Name = "Subscribers")]
        public System.Collections.Generic.List<string> Subscribers;

        public PermissionEntry(
            string Key,
            System.Collections.Generic.List<string> Subscribers
        )
        {
            this.Key = Key;
            this.Subscribers = Subscribers;
        }

        public PermissionEntry()
        {
            this.Key = "";
            this.Subscribers = new();
        }
    }
}
