// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayableCharacter
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "Id")]
        public uint Id;
        [DataMember(Name = "Name")]
        public string Name;
        [DataMember(Name = "MatchId")]
        public uint MatchId;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "rotation")]
        public DbRotation2 Rotation;
        [DataMember(Name = "velocity")]
        public DbVelocity3 Velocity;

        public PlayableCharacter(
            SpacetimeDB.Identity Identity,
            uint Id,
            string Name,
            uint MatchId,
            DbVector3 Position,
            DbRotation2 Rotation,
            DbVelocity3 Velocity
        )
        {
            this.Identity = Identity;
            this.Id = Id;
            this.Name = Name;
            this.MatchId = MatchId;
            this.Position = Position;
            this.Rotation = Rotation;
            this.Velocity = Velocity;
        }

        public PlayableCharacter()
        {
            this.Name = "";
            this.Position = new();
            this.Rotation = new();
            this.Velocity = new();
        }
    }
}
