// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerEffect
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "target_id")]
        public ulong TargetId;
        [DataMember(Name = "sender_id")]
        public ulong SenderId;
        [DataMember(Name = "game_id")]
        public uint GameId;
        [DataMember(Name = "effect_type")]
        public EffectType EffectType;
        [DataMember(Name = "application_information")]
        public ApplicationInformation ApplicationInformation;
        [DataMember(Name = "damage_information")]
        public DamageEffectInformation? DamageInformation;
        [DataMember(Name = "cloak_information")]
        public CloakEffectInformation? CloakInformation;
        [DataMember(Name = "dust_information")]
        public DustEffectInformation? DustInformation;
        [DataMember(Name = "speed_information")]
        public SpeedEffectInformation? SpeedInformation;
        [DataMember(Name = "hypnosis_informaton")]
        public HypnosisEffectInformation? HypnosisInformaton;
        [DataMember(Name = "stunned_information")]
        public StunnedEffectInformation? StunnedInformation;
        [DataMember(Name = "tarot_information")]
        public TarotEffectInformation? TarotInformation;

        public PlayerEffect(
            ulong Id,
            ulong TargetId,
            ulong SenderId,
            uint GameId,
            EffectType EffectType,
            ApplicationInformation ApplicationInformation,
            DamageEffectInformation? DamageInformation,
            CloakEffectInformation? CloakInformation,
            DustEffectInformation? DustInformation,
            SpeedEffectInformation? SpeedInformation,
            HypnosisEffectInformation? HypnosisInformaton,
            StunnedEffectInformation? StunnedInformation,
            TarotEffectInformation? TarotInformation
        )
        {
            this.Id = Id;
            this.TargetId = TargetId;
            this.SenderId = SenderId;
            this.GameId = GameId;
            this.EffectType = EffectType;
            this.ApplicationInformation = ApplicationInformation;
            this.DamageInformation = DamageInformation;
            this.CloakInformation = CloakInformation;
            this.DustInformation = DustInformation;
            this.SpeedInformation = SpeedInformation;
            this.HypnosisInformaton = HypnosisInformaton;
            this.StunnedInformation = StunnedInformation;
            this.TarotInformation = TarotInformation;
        }

        public PlayerEffect()
        {
            this.ApplicationInformation = new();
        }
    }
}
