// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayableCharacter
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "Id")]
        public uint Id;
        [DataMember(Name = "Name")]
        public string Name;
        [DataMember(Name = "MatchId")]
        public uint MatchId;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "rotation")]
        public DbRotation2 Rotation;
        [DataMember(Name = "velocity")]
        public DbVelocity3 Velocity;
        [DataMember(Name = "state")]
        public PlayerState State;
        [DataMember(Name = "Collider")]
        public CapsuleCollider Collider;
        [DataMember(Name = "PlayerPermissionConfig")]
        public System.Collections.Generic.List<PermissionEntry> PlayerPermissionConfig;
        [DataMember(Name = "CollisionEntries")]
        public System.Collections.Generic.List<CollisionEntry> CollisionEntries;
        [DataMember(Name = "IsColliding")]
        public bool IsColliding;
        [DataMember(Name = "CorrectedVelocity")]
        public DbVelocity3 CorrectedVelocity;

        public PlayableCharacter(
            SpacetimeDB.Identity Identity,
            uint Id,
            string Name,
            uint MatchId,
            DbVector3 Position,
            DbRotation2 Rotation,
            DbVelocity3 Velocity,
            PlayerState State,
            CapsuleCollider Collider,
            System.Collections.Generic.List<PermissionEntry> PlayerPermissionConfig,
            System.Collections.Generic.List<CollisionEntry> CollisionEntries,
            bool IsColliding,
            DbVelocity3 CorrectedVelocity
        )
        {
            this.Identity = Identity;
            this.Id = Id;
            this.Name = Name;
            this.MatchId = MatchId;
            this.Position = Position;
            this.Rotation = Rotation;
            this.Velocity = Velocity;
            this.State = State;
            this.Collider = Collider;
            this.PlayerPermissionConfig = PlayerPermissionConfig;
            this.CollisionEntries = CollisionEntries;
            this.IsColliding = IsColliding;
            this.CorrectedVelocity = CorrectedVelocity;
        }

        public PlayableCharacter()
        {
            this.Name = "";
            this.Position = new();
            this.Rotation = new();
            this.Velocity = new();
            this.Collider = new();
            this.PlayerPermissionConfig = new();
            this.CollisionEntries = new();
            this.CorrectedVelocity = new();
        }
    }
}
