// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerEffect
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "target_id")]
        public ulong TargetId;
        [DataMember(Name = "sender_id")]
        public ulong SenderId;
        [DataMember(Name = "game_id")]
        public uint GameId;
        [DataMember(Name = "effect_info")]
        public Effect EffectInfo;
        [DataMember(Name = "effect_type")]
        public EffectType EffectType;

        public PlayerEffect(
            ulong Id,
            ulong TargetId,
            ulong SenderId,
            uint GameId,
            Effect EffectInfo,
            EffectType EffectType
        )
        {
            this.Id = Id;
            this.TargetId = TargetId;
            this.SenderId = SenderId;
            this.GameId = GameId;
            this.EffectInfo = EffectInfo;
            this.EffectType = EffectType;
        }

        public PlayerEffect()
        {
            this.EffectInfo = new();
        }
    }
}
