// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerEffect
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "target_id")]
        public ulong TargetId;
        [DataMember(Name = "game_id")]
        public uint GameId;
        [DataMember(Name = "effect_type")]
        public EffectType EffectType;
        [DataMember(Name = "application_information")]
        public ApplicationInformation ApplicationInformation;
        [DataMember(Name = "damage_information")]
        public DamageInformation? DamageInformation;

        public PlayerEffect(
            ulong Id,
            ulong TargetId,
            uint GameId,
            EffectType EffectType,
            ApplicationInformation ApplicationInformation,
            DamageInformation? DamageInformation
        )
        {
            this.Id = Id;
            this.TargetId = TargetId;
            this.GameId = GameId;
            this.EffectType = EffectType;
            this.ApplicationInformation = ApplicationInformation;
            this.DamageInformation = DamageInformation;
        }

        public PlayerEffect()
        {
            this.ApplicationInformation = new();
        }
    }
}
