// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Projectile
    {
        [DataMember(Name = "Id")]
        public uint Id;
        [DataMember(Name = "OwnerIdentity")]
        public SpacetimeDB.Identity OwnerIdentity;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "velocity")]
        public DbVelocity3 Velocity;
        [DataMember(Name = "ProjectileType")]
        public ProjectileType ProjectileType;

        public Projectile(
            uint Id,
            SpacetimeDB.Identity OwnerIdentity,
            DbVector3 Position,
            DbVelocity3 Velocity,
            ProjectileType ProjectileType
        )
        {
            this.Id = Id;
            this.OwnerIdentity = OwnerIdentity;
            this.Position = Position;
            this.Velocity = Velocity;
            this.ProjectileType = ProjectileType;
        }

        public Projectile()
        {
            this.Position = new();
            this.Velocity = new();
        }
    }
}
