// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RespawnTimersTimer
    {
        [DataMember(Name = "scheduled_id")]
        public ulong ScheduledId;
        [DataMember(Name = "scheduled_at")]
        public SpacetimeDB.ScheduleAt ScheduledAt;
        [DataMember(Name = "game_id")]
        public uint GameId;
        [DataMember(Name = "player")]
        public Player Player;

        public RespawnTimersTimer(
            ulong ScheduledId,
            SpacetimeDB.ScheduleAt ScheduledAt,
            uint GameId,
            Player Player
        )
        {
            this.ScheduledId = ScheduledId;
            this.ScheduledAt = ScheduledAt;
            this.GameId = GameId;
            this.Player = Player;
        }

        public RespawnTimersTimer()
        {
            this.ScheduledAt = null!;
            this.Player = new();
        }
    }
}
