// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SpeedEffectInformation
    {
        [DataMember(Name = "speed_multiplier")]
        public float SpeedMultiplier;

        public SpeedEffectInformation(float SpeedMultiplier)
        {
            this.SpeedMultiplier = SpeedMultiplier;
        }

        public SpeedEffectInformation()
        {
        }
    }
}
