// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class StatelessTimer
    {
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "state")]
        public StatelessTimerState State;
        [DataMember(Name = "cooldown_time")]
        public float CooldownTime;
        [DataMember(Name = "application_time")]
        public float ApplicationTime;
        [DataMember(Name = "current_time")]
        public float CurrentTime;

        public StatelessTimer(
            string Name,
            StatelessTimerState State,
            float CooldownTime,
            float ApplicationTime,
            float CurrentTime
        )
        {
            this.Name = Name;
            this.State = State;
            this.CooldownTime = CooldownTime;
            this.ApplicationTime = ApplicationTime;
            this.CurrentTime = CurrentTime;
        }

        public StatelessTimer()
        {
            this.Name = "";
        }
    }
}
