// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ThrowingCard
    {
        [DataMember(Name = "Effects")]
        public System.Collections.Generic.List<Effect> Effects;

        public ThrowingCard(System.Collections.Generic.List<Effect> Effects)
        {
            this.Effects = Effects;
        }

        public ThrowingCard()
        {
            this.Effects = new();
        }
    }
}
