// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Timer
    {
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "state")]
        public TimerState State;
        [DataMember(Name = "cooldown_time")]
        public float CooldownTime;
        [DataMember(Name = "use_finished_time")]
        public float UseFinishedTime;
        [DataMember(Name = "current_time")]
        public float CurrentTime;

        public Timer(
            string Name,
            TimerState State,
            float CooldownTime,
            float UseFinishedTime,
            float CurrentTime
        )
        {
            this.Name = Name;
            this.State = State;
            this.CooldownTime = CooldownTime;
            this.UseFinishedTime = UseFinishedTime;
            this.CurrentTime = CurrentTime;
        }

        public Timer()
        {
            this.Name = "";
        }
    }
}
