// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Timer
    {
        [DataMember(Name = "Name")]
        public string Name;
        [DataMember(Name = "ResetTime")]
        public float ResetTime;
        [DataMember(Name = "CurrentTime")]
        public float CurrentTime;

        public Timer(
            string Name,
            float ResetTime,
            float CurrentTime
        )
        {
            this.Name = Name;
            this.ResetTime = ResetTime;
            this.CurrentTime = CurrentTime;
        }

        public Timer()
        {
            this.Name = "";
        }
    }
}
