// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class UnitTestMode
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "enabled")]
        public bool Enabled;

        public UnitTestMode(
            uint Id,
            bool Enabled
        )
        {
            this.Id = Id;
            this.Enabled = Enabled;
        }

        public UnitTestMode()
        {
        }
    }
}
