// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddCollisionEntryMagicianHandler(ReducerEventContext ctx, CollisionEntry entry, SpacetimeDB.Identity targetIdentity);
        public event AddCollisionEntryMagicianHandler? OnAddCollisionEntryMagician;

        public void AddCollisionEntryMagician(CollisionEntry entry, SpacetimeDB.Identity targetIdentity)
        {
            conn.InternalCallReducer(new Reducer.AddCollisionEntryMagician(entry, targetIdentity), this.SetCallReducerFlags.AddCollisionEntryMagicianFlags);
        }

        public bool InvokeAddCollisionEntryMagician(ReducerEventContext ctx, Reducer.AddCollisionEntryMagician args)
        {
            if (OnAddCollisionEntryMagician == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAddCollisionEntryMagician(
                ctx,
                args.Entry,
                args.TargetIdentity
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddCollisionEntryMagician : Reducer, IReducerArgs
        {
            [DataMember(Name = "Entry")]
            public CollisionEntry Entry;
            [DataMember(Name = "TargetIdentity")]
            public SpacetimeDB.Identity TargetIdentity;

            public AddCollisionEntryMagician(
                CollisionEntry Entry,
                SpacetimeDB.Identity TargetIdentity
            )
            {
                this.Entry = Entry;
                this.TargetIdentity = TargetIdentity;
            }

            public AddCollisionEntryMagician()
            {
                this.Entry = new();
            }

            string IReducerArgs.ReducerName => "AddCollisionEntryMagician";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AddCollisionEntryMagicianFlags;
        public void AddCollisionEntryMagician(CallReducerFlags flags) => AddCollisionEntryMagicianFlags = flags;
    }
}
