// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddCollisionEntryHandler(ReducerEventContext ctx, CollisionEntry entry);
        public event AddCollisionEntryHandler? OnAddCollisionEntry;

        public void AddCollisionEntry(CollisionEntry entry)
        {
            conn.InternalCallReducer(new Reducer.AddCollisionEntry(entry), this.SetCallReducerFlags.AddCollisionEntryFlags);
        }

        public bool InvokeAddCollisionEntry(ReducerEventContext ctx, Reducer.AddCollisionEntry args)
        {
            if (OnAddCollisionEntry == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAddCollisionEntry(
                ctx,
                args.Entry
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddCollisionEntry : Reducer, IReducerArgs
        {
            [DataMember(Name = "Entry")]
            public CollisionEntry Entry;

            public AddCollisionEntry(CollisionEntry Entry)
            {
                this.Entry = Entry;
            }

            public AddCollisionEntry()
            {
                this.Entry = new();
            }

            string IReducerArgs.ReducerName => "AddCollisionEntry";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AddCollisionEntryFlags;
        public void AddCollisionEntry(CallReducerFlags flags) => AddCollisionEntryFlags = flags;
    }
}
