// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddEffectsToTableHandler(ReducerEventContext ctx, System.Collections.Generic.List<SpacetimeDB.Types.Effect> effects, ulong magicianId, uint gameId);
        public event AddEffectsToTableHandler? OnAddEffectsToTable;

        public void AddEffectsToTable(System.Collections.Generic.List<SpacetimeDB.Types.Effect> effects, ulong magicianId, uint gameId)
        {
            conn.InternalCallReducer(new Reducer.AddEffectsToTable(effects, magicianId, gameId), this.SetCallReducerFlags.AddEffectsToTableFlags);
        }

        public bool InvokeAddEffectsToTable(ReducerEventContext ctx, Reducer.AddEffectsToTable args)
        {
            if (OnAddEffectsToTable == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAddEffectsToTable(
                ctx,
                args.Effects,
                args.MagicianId,
                args.GameId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddEffectsToTable : Reducer, IReducerArgs
        {
            [DataMember(Name = "effects")]
            public System.Collections.Generic.List<Effect> Effects;
            [DataMember(Name = "magician_id")]
            public ulong MagicianId;
            [DataMember(Name = "game_id")]
            public uint GameId;

            public AddEffectsToTable(
                System.Collections.Generic.List<Effect> Effects,
                ulong MagicianId,
                uint GameId
            )
            {
                this.Effects = Effects;
                this.MagicianId = MagicianId;
                this.GameId = GameId;
            }

            public AddEffectsToTable()
            {
                this.Effects = new();
            }

            string IReducerArgs.ReducerName => "add_effects_to_table";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AddEffectsToTableFlags;
        public void AddEffectsToTable(CallReducerFlags flags) => AddEffectsToTableFlags = flags;
    }
}
