// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddEffectsToMagicianHandler(ReducerEventContext ctx, System.Collections.Generic.List<SpacetimeDB.Types.Effect> effects, ulong targetMagicianId);
        public event AddEffectsToMagicianHandler? OnAddEffectsToMagician;

        public void AddEffectsToMagician(System.Collections.Generic.List<SpacetimeDB.Types.Effect> effects, ulong targetMagicianId)
        {
            conn.InternalCallReducer(new Reducer.AddEffectsToMagician(effects, targetMagicianId), this.SetCallReducerFlags.AddEffectsToMagicianFlags);
        }

        public bool InvokeAddEffectsToMagician(ReducerEventContext ctx, Reducer.AddEffectsToMagician args)
        {
            if (OnAddEffectsToMagician == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAddEffectsToMagician(
                ctx,
                args.Effects,
                args.TargetMagicianId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddEffectsToMagician : Reducer, IReducerArgs
        {
            [DataMember(Name = "effects")]
            public System.Collections.Generic.List<Effect> Effects;
            [DataMember(Name = "target_magician_id")]
            public ulong TargetMagicianId;

            public AddEffectsToMagician(
                System.Collections.Generic.List<Effect> Effects,
                ulong TargetMagicianId
            )
            {
                this.Effects = Effects;
                this.TargetMagicianId = TargetMagicianId;
            }

            public AddEffectsToMagician()
            {
                this.Effects = new();
            }

            string IReducerArgs.ReducerName => "add_effects_to_magician";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AddEffectsToMagicianFlags;
        public void AddEffectsToMagician(CallReducerFlags flags) => AddEffectsToMagicianFlags = flags;
    }
}
