// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ApplyGravityMagicianHandler(ReducerEventContext ctx, SpacetimeDB.Types.GravityTimerMagician timer);
        public event ApplyGravityMagicianHandler? OnApplyGravityMagician;

        public void ApplyGravityMagician(SpacetimeDB.Types.GravityTimerMagician timer)
        {
            conn.InternalCallReducer(new Reducer.ApplyGravityMagician(timer), this.SetCallReducerFlags.ApplyGravityMagicianFlags);
        }

        public bool InvokeApplyGravityMagician(ReducerEventContext ctx, Reducer.ApplyGravityMagician args)
        {
            if (OnApplyGravityMagician == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnApplyGravityMagician(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ApplyGravityMagician : Reducer, IReducerArgs
        {
            [DataMember(Name = "timer")]
            public GravityTimerMagician Timer;

            public ApplyGravityMagician(GravityTimerMagician Timer)
            {
                this.Timer = Timer;
            }

            public ApplyGravityMagician()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "apply_gravity_magician";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ApplyGravityMagicianFlags;
        public void ApplyGravityMagician(CallReducerFlags flags) => ApplyGravityMagicianFlags = flags;
    }
}
