// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ApplyGravityHandler(ReducerEventContext ctx, GravityTimer timer);
        public event ApplyGravityHandler? OnApplyGravity;

        public void ApplyGravity(GravityTimer timer)
        {
            conn.InternalCallReducer(new Reducer.ApplyGravity(timer), this.SetCallReducerFlags.ApplyGravityFlags);
        }

        public bool InvokeApplyGravity(ReducerEventContext ctx, Reducer.ApplyGravity args)
        {
            if (OnApplyGravity == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnApplyGravity(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ApplyGravity : Reducer, IReducerArgs
        {
            [DataMember(Name = "timer")]
            public GravityTimer Timer;

            public ApplyGravity(GravityTimer Timer)
            {
                this.Timer = Timer;
            }

            public ApplyGravity()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "ApplyGravity";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ApplyGravityFlags;
        public void ApplyGravity(CallReducerFlags flags) => ApplyGravityFlags = flags;
    }
}
