// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void HandleGameEndHandler(ReducerEventContext ctx, SpacetimeDB.Types.GameTimersTimer timer);
        public event HandleGameEndHandler? OnHandleGameEnd;

        public void HandleGameEnd(SpacetimeDB.Types.GameTimersTimer timer)
        {
            conn.InternalCallReducer(new Reducer.HandleGameEnd(timer), this.SetCallReducerFlags.HandleGameEndFlags);
        }

        public bool InvokeHandleGameEnd(ReducerEventContext ctx, Reducer.HandleGameEnd args)
        {
            if (OnHandleGameEnd == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnHandleGameEnd(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class HandleGameEnd : Reducer, IReducerArgs
        {
            [DataMember(Name = "timer")]
            public GameTimersTimer Timer;

            public HandleGameEnd(GameTimersTimer Timer)
            {
                this.Timer = Timer;
            }

            public HandleGameEnd()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "handle_game_end";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags HandleGameEndFlags;
        public void HandleGameEnd(CallReducerFlags flags) => HandleGameEndFlags = flags;
    }
}
