// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void HandleActionExitRequestHandler(ReducerEventContext ctx, PlayerState newPlayerState);
        public event HandleActionExitRequestHandler? OnHandleActionExitRequest;

        public void HandleActionExitRequest(PlayerState newPlayerState)
        {
            conn.InternalCallReducer(new Reducer.HandleActionExitRequest(newPlayerState), this.SetCallReducerFlags.HandleActionExitRequestFlags);
        }

        public bool InvokeHandleActionExitRequest(ReducerEventContext ctx, Reducer.HandleActionExitRequest args)
        {
            if (OnHandleActionExitRequest == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnHandleActionExitRequest(
                ctx,
                args.NewPlayerState
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class HandleActionExitRequest : Reducer, IReducerArgs
        {
            [DataMember(Name = "newPlayerState")]
            public PlayerState NewPlayerState;

            public HandleActionExitRequest(PlayerState NewPlayerState)
            {
                this.NewPlayerState = NewPlayerState;
            }

            public HandleActionExitRequest()
            {
            }

            string IReducerArgs.ReducerName => "HandleActionExitRequest";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags HandleActionExitRequestFlags;
        public void HandleActionExitRequest(CallReducerFlags flags) => HandleActionExitRequestFlags = flags;
    }
}
