// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void HandleActionChangeRequestMagicianHandler(ReducerEventContext ctx, ActionRequestMagician request);
        public event HandleActionChangeRequestMagicianHandler? OnHandleActionChangeRequestMagician;

        public void HandleActionChangeRequestMagician(ActionRequestMagician request)
        {
            conn.InternalCallReducer(new Reducer.HandleActionChangeRequestMagician(request), this.SetCallReducerFlags.HandleActionChangeRequestMagicianFlags);
        }

        public bool InvokeHandleActionChangeRequestMagician(ReducerEventContext ctx, Reducer.HandleActionChangeRequestMagician args)
        {
            if (OnHandleActionChangeRequestMagician == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnHandleActionChangeRequestMagician(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class HandleActionChangeRequestMagician : Reducer, IReducerArgs
        {
            [DataMember(Name = "Request")]
            public ActionRequestMagician Request;

            public HandleActionChangeRequestMagician(ActionRequestMagician Request)
            {
                this.Request = Request;
            }

            public HandleActionChangeRequestMagician()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "HandleActionChangeRequestMagician";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags HandleActionChangeRequestMagicianFlags;
        public void HandleActionChangeRequestMagician(CallReducerFlags flags) => HandleActionChangeRequestMagicianFlags = flags;
    }
}
