// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void HandleMagicianTimersHandler(ReducerEventContext ctx, SpacetimeDB.Types.HandleMagicianTimersTimer timer);
        public event HandleMagicianTimersHandler? OnHandleMagicianTimers;

        public void HandleMagicianTimers(SpacetimeDB.Types.HandleMagicianTimersTimer timer)
        {
            conn.InternalCallReducer(new Reducer.HandleMagicianTimers(timer), this.SetCallReducerFlags.HandleMagicianTimersFlags);
        }

        public bool InvokeHandleMagicianTimers(ReducerEventContext ctx, Reducer.HandleMagicianTimers args)
        {
            if (OnHandleMagicianTimers == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnHandleMagicianTimers(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class HandleMagicianTimers : Reducer, IReducerArgs
        {
            [DataMember(Name = "timer")]
            public HandleMagicianTimersTimer Timer;

            public HandleMagicianTimers(HandleMagicianTimersTimer Timer)
            {
                this.Timer = Timer;
            }

            public HandleMagicianTimers()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "handle_magician_timers";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags HandleMagicianTimersFlags;
        public void HandleMagicianTimers(CallReducerFlags flags) => HandleMagicianTimersFlags = flags;
    }
}
