// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void HandleBulletPlayerCollisionHandler(ReducerEventContext ctx, SpacetimeDB.Identity playerIdentity, uint bulletId);
        public event HandleBulletPlayerCollisionHandler? OnHandleBulletPlayerCollision;

        public void HandleBulletPlayerCollision(SpacetimeDB.Identity playerIdentity, uint bulletId)
        {
            conn.InternalCallReducer(new Reducer.HandleBulletPlayerCollision(playerIdentity, bulletId), this.SetCallReducerFlags.HandleBulletPlayerCollisionFlags);
        }

        public bool InvokeHandleBulletPlayerCollision(ReducerEventContext ctx, Reducer.HandleBulletPlayerCollision args)
        {
            if (OnHandleBulletPlayerCollision == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnHandleBulletPlayerCollision(
                ctx,
                args.PlayerIdentity,
                args.BulletId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class HandleBulletPlayerCollision : Reducer, IReducerArgs
        {
            [DataMember(Name = "PlayerIdentity")]
            public SpacetimeDB.Identity PlayerIdentity;
            [DataMember(Name = "BulletId")]
            public uint BulletId;

            public HandleBulletPlayerCollision(
                SpacetimeDB.Identity PlayerIdentity,
                uint BulletId
            )
            {
                this.PlayerIdentity = PlayerIdentity;
                this.BulletId = BulletId;
            }

            public HandleBulletPlayerCollision()
            {
            }

            string IReducerArgs.ReducerName => "HandleBulletPlayerCollision";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags HandleBulletPlayerCollisionFlags;
        public void HandleBulletPlayerCollision(CallReducerFlags flags) => HandleBulletPlayerCollisionFlags = flags;
    }
}
