// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void HandleMagicianStatelessTimersHandler(ReducerEventContext ctx, SpacetimeDB.Types.HandleMagicianStatelessTimersTimer timer);
        public event HandleMagicianStatelessTimersHandler? OnHandleMagicianStatelessTimers;

        public void HandleMagicianStatelessTimers(SpacetimeDB.Types.HandleMagicianStatelessTimersTimer timer)
        {
            conn.InternalCallReducer(new Reducer.HandleMagicianStatelessTimers(timer), this.SetCallReducerFlags.HandleMagicianStatelessTimersFlags);
        }

        public bool InvokeHandleMagicianStatelessTimers(ReducerEventContext ctx, Reducer.HandleMagicianStatelessTimers args)
        {
            if (OnHandleMagicianStatelessTimers == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnHandleMagicianStatelessTimers(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class HandleMagicianStatelessTimers : Reducer, IReducerArgs
        {
            [DataMember(Name = "timer")]
            public HandleMagicianStatelessTimersTimer Timer;

            public HandleMagicianStatelessTimers(HandleMagicianStatelessTimersTimer Timer)
            {
                this.Timer = Timer;
            }

            public HandleMagicianStatelessTimers()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "handle_magician_stateless_timers";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags HandleMagicianStatelessTimersFlags;
        public void HandleMagicianStatelessTimers(CallReducerFlags flags) => HandleMagicianStatelessTimersFlags = flags;
    }
}
