// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void HandlePlayerEffectsTableHandler(ReducerEventContext ctx, SpacetimeDB.Types.PlayerEffectsTableTimer timer);
        public event HandlePlayerEffectsTableHandler? OnHandlePlayerEffectsTable;

        public void HandlePlayerEffectsTable(SpacetimeDB.Types.PlayerEffectsTableTimer timer)
        {
            conn.InternalCallReducer(new Reducer.HandlePlayerEffectsTable(timer), this.SetCallReducerFlags.HandlePlayerEffectsTableFlags);
        }

        public bool InvokeHandlePlayerEffectsTable(ReducerEventContext ctx, Reducer.HandlePlayerEffectsTable args)
        {
            if (OnHandlePlayerEffectsTable == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnHandlePlayerEffectsTable(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class HandlePlayerEffectsTable : Reducer, IReducerArgs
        {
            [DataMember(Name = "timer")]
            public PlayerEffectsTableTimer Timer;

            public HandlePlayerEffectsTable(PlayerEffectsTableTimer Timer)
            {
                this.Timer = Timer;
            }

            public HandlePlayerEffectsTable()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "handle_player_effects_table";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags HandlePlayerEffectsTableFlags;
        public void HandlePlayerEffectsTable(CallReducerFlags flags) => HandlePlayerEffectsTableFlags = flags;
    }
}
