// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void HandleRespawnHandler(ReducerEventContext ctx, SpacetimeDB.Types.RespawnTimersTimer timer);
        public event HandleRespawnHandler? OnHandleRespawn;

        public void HandleRespawn(SpacetimeDB.Types.RespawnTimersTimer timer)
        {
            conn.InternalCallReducer(new Reducer.HandleRespawn(timer), this.SetCallReducerFlags.HandleRespawnFlags);
        }

        public bool InvokeHandleRespawn(ReducerEventContext ctx, Reducer.HandleRespawn args)
        {
            if (OnHandleRespawn == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnHandleRespawn(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class HandleRespawn : Reducer, IReducerArgs
        {
            [DataMember(Name = "timer")]
            public RespawnTimersTimer Timer;

            public HandleRespawn(RespawnTimersTimer Timer)
            {
                this.Timer = Timer;
            }

            public HandleRespawn()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "handle_respawn";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags HandleRespawnFlags;
        public void HandleRespawn(CallReducerFlags flags) => HandleRespawnFlags = flags;
    }
}
