// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void HandleMovementRequestHandler(ReducerEventContext ctx, DbVelocity3 vel);
        public event HandleMovementRequestHandler? OnHandleMovementRequest;

        public void HandleMovementRequest(DbVelocity3 vel)
        {
            conn.InternalCallReducer(new Reducer.HandleMovementRequest(vel), this.SetCallReducerFlags.HandleMovementRequestFlags);
        }

        public bool InvokeHandleMovementRequest(ReducerEventContext ctx, Reducer.HandleMovementRequest args)
        {
            if (OnHandleMovementRequest == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnHandleMovementRequest(
                ctx,
                args.Vel
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class HandleMovementRequest : Reducer, IReducerArgs
        {
            [DataMember(Name = "vel")]
            public DbVelocity3 Vel;

            public HandleMovementRequest(DbVelocity3 Vel)
            {
                this.Vel = Vel;
            }

            public HandleMovementRequest()
            {
                this.Vel = new();
            }

            string IReducerArgs.ReducerName => "HandleMovementRequest";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags HandleMovementRequestFlags;
        public void HandleMovementRequest(CallReducerFlags flags) => HandleMovementRequestFlags = flags;
    }
}
