// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void HandleActionEnterRequestHandler(ReducerEventContext ctx, ActionRequest request);
        public event HandleActionEnterRequestHandler? OnHandleActionEnterRequest;

        public void HandleActionEnterRequest(ActionRequest request)
        {
            conn.InternalCallReducer(new Reducer.HandleActionEnterRequest(request), this.SetCallReducerFlags.HandleActionEnterRequestFlags);
        }

        public bool InvokeHandleActionEnterRequest(ReducerEventContext ctx, Reducer.HandleActionEnterRequest args)
        {
            if (OnHandleActionEnterRequest == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnHandleActionEnterRequest(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class HandleActionEnterRequest : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public ActionRequest Request;

            public HandleActionEnterRequest(ActionRequest Request)
            {
                this.Request = Request;
            }

            public HandleActionEnterRequest()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "HandleActionEnterRequest";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags HandleActionEnterRequestFlags;
        public void HandleActionEnterRequest(CallReducerFlags flags) => HandleActionEnterRequestFlags = flags;
    }
}
