// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void HandleMagicianEffectsHandler(ReducerEventContext ctx, SpacetimeDB.Types.HandleMagicianEffectsTimer timer);
        public event HandleMagicianEffectsHandler? OnHandleMagicianEffects;

        public void HandleMagicianEffects(SpacetimeDB.Types.HandleMagicianEffectsTimer timer)
        {
            conn.InternalCallReducer(new Reducer.HandleMagicianEffects(timer), this.SetCallReducerFlags.HandleMagicianEffectsFlags);
        }

        public bool InvokeHandleMagicianEffects(ReducerEventContext ctx, Reducer.HandleMagicianEffects args)
        {
            if (OnHandleMagicianEffects == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnHandleMagicianEffects(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class HandleMagicianEffects : Reducer, IReducerArgs
        {
            [DataMember(Name = "timer")]
            public HandleMagicianEffectsTimer Timer;

            public HandleMagicianEffects(HandleMagicianEffectsTimer Timer)
            {
                this.Timer = Timer;
            }

            public HandleMagicianEffects()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "handle_magician_effects";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags HandleMagicianEffectsFlags;
        public void HandleMagicianEffects(CallReducerFlags flags) => HandleMagicianEffectsFlags = flags;
    }
}
