// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MoveMagicians2Handler(ReducerEventContext ctx, SpacetimeDB.Types.MoveAllMagiciansTimer timer);
        public event MoveMagicians2Handler? OnMoveMagicians2;

        public void MoveMagicians2(SpacetimeDB.Types.MoveAllMagiciansTimer timer)
        {
            conn.InternalCallReducer(new Reducer.MoveMagicians2(timer), this.SetCallReducerFlags.MoveMagicians2Flags);
        }

        public bool InvokeMoveMagicians2(ReducerEventContext ctx, Reducer.MoveMagicians2 args)
        {
            if (OnMoveMagicians2 == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnMoveMagicians2(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MoveMagicians2 : Reducer, IReducerArgs
        {
            [DataMember(Name = "timer")]
            public MoveAllMagiciansTimer Timer;

            public MoveMagicians2(MoveAllMagiciansTimer Timer)
            {
                this.Timer = Timer;
            }

            public MoveMagicians2()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "move_magicians2";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags MoveMagicians2Flags;
        public void MoveMagicians2(CallReducerFlags flags) => MoveMagicians2Flags = flags;
    }
}
