// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MoveThrowingCardsHandler(ReducerEventContext ctx, MoveThrowingCardsTimer timer);
        public event MoveThrowingCardsHandler? OnMoveThrowingCards;

        public void MoveThrowingCards(MoveThrowingCardsTimer timer)
        {
            conn.InternalCallReducer(new Reducer.MoveThrowingCards(timer), this.SetCallReducerFlags.MoveThrowingCardsFlags);
        }

        public bool InvokeMoveThrowingCards(ReducerEventContext ctx, Reducer.MoveThrowingCards args)
        {
            if (OnMoveThrowingCards == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnMoveThrowingCards(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MoveThrowingCards : Reducer, IReducerArgs
        {
            [DataMember(Name = "timer")]
            public MoveThrowingCardsTimer Timer;

            public MoveThrowingCards(MoveThrowingCardsTimer Timer)
            {
                this.Timer = Timer;
            }

            public MoveThrowingCards()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "MoveThrowingCards";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags MoveThrowingCardsFlags;
        public void MoveThrowingCards(CallReducerFlags flags) => MoveThrowingCardsFlags = flags;
    }
}
