// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MoveMagiciansHandler(ReducerEventContext ctx, SpacetimeDB.Types.MoveAllMagiciansTimer timer);
        public event MoveMagiciansHandler? OnMoveMagicians;

        public void MoveMagicians(SpacetimeDB.Types.MoveAllMagiciansTimer timer)
        {
            conn.InternalCallReducer(new Reducer.MoveMagicians(timer), this.SetCallReducerFlags.MoveMagiciansFlags);
        }

        public bool InvokeMoveMagicians(ReducerEventContext ctx, Reducer.MoveMagicians args)
        {
            if (OnMoveMagicians == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnMoveMagicians(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MoveMagicians : Reducer, IReducerArgs
        {
            [DataMember(Name = "timer")]
            public MoveAllMagiciansTimer Timer;

            public MoveMagicians(MoveAllMagiciansTimer Timer)
            {
                this.Timer = Timer;
            }

            public MoveMagicians()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "move_magicians";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags MoveMagiciansFlags;
        public void MoveMagicians(CallReducerFlags flags) => MoveMagiciansFlags = flags;
    }
}
