// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MoveMagiciansCcdHandler(ReducerEventContext ctx, MoveAllMagiciansTimer timer);
        public event MoveMagiciansCcdHandler? OnMoveMagiciansCcd;

        public void MoveMagiciansCcd(MoveAllMagiciansTimer timer)
        {
            conn.InternalCallReducer(new Reducer.MoveMagiciansCcd(timer), this.SetCallReducerFlags.MoveMagiciansCcdFlags);
        }

        public bool InvokeMoveMagiciansCcd(ReducerEventContext ctx, Reducer.MoveMagiciansCcd args)
        {
            if (OnMoveMagiciansCcd == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnMoveMagiciansCcd(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MoveMagiciansCcd : Reducer, IReducerArgs
        {
            [DataMember(Name = "Timer")]
            public MoveAllMagiciansTimer Timer;

            public MoveMagiciansCcd(MoveAllMagiciansTimer Timer)
            {
                this.Timer = Timer;
            }

            public MoveMagiciansCcd()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "MoveMagiciansCCD";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags MoveMagiciansCcdFlags;
        public void MoveMagiciansCcd(CallReducerFlags flags) => MoveMagiciansCcdFlags = flags;
    }
}
