// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MoveProjectilesHandler(ReducerEventContext ctx, MoveProjectilesTimer timer);
        public event MoveProjectilesHandler? OnMoveProjectiles;

        public void MoveProjectiles(MoveProjectilesTimer timer)
        {
            conn.InternalCallReducer(new Reducer.MoveProjectiles(timer), this.SetCallReducerFlags.MoveProjectilesFlags);
        }

        public bool InvokeMoveProjectiles(ReducerEventContext ctx, Reducer.MoveProjectiles args)
        {
            if (OnMoveProjectiles == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnMoveProjectiles(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MoveProjectiles : Reducer, IReducerArgs
        {
            [DataMember(Name = "timer")]
            public MoveProjectilesTimer Timer;

            public MoveProjectiles(MoveProjectilesTimer Timer)
            {
                this.Timer = Timer;
            }

            public MoveProjectiles()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "MoveProjectiles";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags MoveProjectilesFlags;
        public void MoveProjectiles(CallReducerFlags flags) => MoveProjectilesFlags = flags;
    }
}
