// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PingHandler(ReducerEventContext ctx, uint sequence);
        public event PingHandler? OnPing;

        public void Ping(uint sequence)
        {
            conn.InternalCallReducer(new Reducer.Ping(sequence), this.SetCallReducerFlags.PingFlags);
        }

        public bool InvokePing(ReducerEventContext ctx, Reducer.Ping args)
        {
            if (OnPing == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPing(
                ctx,
                args.Sequence
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Ping : Reducer, IReducerArgs
        {
            [DataMember(Name = "sequence")]
            public uint Sequence;

            public Ping(uint Sequence)
            {
                this.Sequence = Sequence;
            }

            public Ping()
            {
            }

            string IReducerArgs.ReducerName => "ping";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags PingFlags;
        public void Ping(CallReducerFlags flags) => PingFlags = flags;
    }
}
