// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RemovePlayerPlayerCollisionHandler(ReducerEventContext ctx, uint playerId);
        public event RemovePlayerPlayerCollisionHandler? OnRemovePlayerPlayerCollision;

        public void RemovePlayerPlayerCollision(uint playerId)
        {
            conn.InternalCallReducer(new Reducer.RemovePlayerPlayerCollision(playerId), this.SetCallReducerFlags.RemovePlayerPlayerCollisionFlags);
        }

        public bool InvokeRemovePlayerPlayerCollision(ReducerEventContext ctx, Reducer.RemovePlayerPlayerCollision args)
        {
            if (OnRemovePlayerPlayerCollision == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRemovePlayerPlayerCollision(
                ctx,
                args.PlayerId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RemovePlayerPlayerCollision : Reducer, IReducerArgs
        {
            [DataMember(Name = "playerId")]
            public uint PlayerId;

            public RemovePlayerPlayerCollision(uint PlayerId)
            {
                this.PlayerId = PlayerId;
            }

            public RemovePlayerPlayerCollision()
            {
            }

            string IReducerArgs.ReducerName => "RemovePlayerPlayerCollision";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags RemovePlayerPlayerCollisionFlags;
        public void RemovePlayerPlayerCollision(CallReducerFlags flags) => RemovePlayerPlayerCollisionFlags = flags;
    }
}
