// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetCollisionResolvedVelocityHandler(ReducerEventContext ctx, DbVelocity3 velocity);
        public event SetCollisionResolvedVelocityHandler? OnSetCollisionResolvedVelocity;

        public void SetCollisionResolvedVelocity(DbVelocity3 velocity)
        {
            conn.InternalCallReducer(new Reducer.SetCollisionResolvedVelocity(velocity), this.SetCallReducerFlags.SetCollisionResolvedVelocityFlags);
        }

        public bool InvokeSetCollisionResolvedVelocity(ReducerEventContext ctx, Reducer.SetCollisionResolvedVelocity args)
        {
            if (OnSetCollisionResolvedVelocity == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetCollisionResolvedVelocity(
                ctx,
                args.Velocity
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetCollisionResolvedVelocity : Reducer, IReducerArgs
        {
            [DataMember(Name = "Velocity")]
            public DbVelocity3 Velocity;

            public SetCollisionResolvedVelocity(DbVelocity3 Velocity)
            {
                this.Velocity = Velocity;
            }

            public SetCollisionResolvedVelocity()
            {
                this.Velocity = new();
            }

            string IReducerArgs.ReducerName => "SetCollisionResolvedVelocity";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SetCollisionResolvedVelocityFlags;
        public void SetCollisionResolvedVelocity(CallReducerFlags flags) => SetCollisionResolvedVelocityFlags = flags;
    }
}
