// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SpawnThrowingCardHandler(ReducerEventContext ctx, DbVector3 cameraPositionOffset, float cameraYawOffset, float cameraPitchOffset, DbVector3 handPositionOffset, float maxDistance);
        public event SpawnThrowingCardHandler? OnSpawnThrowingCard;

        public void SpawnThrowingCard(DbVector3 cameraPositionOffset, float cameraYawOffset, float cameraPitchOffset, DbVector3 handPositionOffset, float maxDistance)
        {
            conn.InternalCallReducer(new Reducer.SpawnThrowingCard(cameraPositionOffset, cameraYawOffset, cameraPitchOffset, handPositionOffset, maxDistance), this.SetCallReducerFlags.SpawnThrowingCardFlags);
        }

        public bool InvokeSpawnThrowingCard(ReducerEventContext ctx, Reducer.SpawnThrowingCard args)
        {
            if (OnSpawnThrowingCard == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSpawnThrowingCard(
                ctx,
                args.CameraPositionOffset,
                args.CameraYawOffset,
                args.CameraPitchOffset,
                args.HandPositionOffset,
                args.MaxDistance
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SpawnThrowingCard : Reducer, IReducerArgs
        {
            [DataMember(Name = "CameraPositionOffset")]
            public DbVector3 CameraPositionOffset;
            [DataMember(Name = "CameraYawOffset")]
            public float CameraYawOffset;
            [DataMember(Name = "CameraPitchOffset")]
            public float CameraPitchOffset;
            [DataMember(Name = "HandPositionOffset")]
            public DbVector3 HandPositionOffset;
            [DataMember(Name = "MaxDistance")]
            public float MaxDistance;

            public SpawnThrowingCard(
                DbVector3 CameraPositionOffset,
                float CameraYawOffset,
                float CameraPitchOffset,
                DbVector3 HandPositionOffset,
                float MaxDistance
            )
            {
                this.CameraPositionOffset = CameraPositionOffset;
                this.CameraYawOffset = CameraYawOffset;
                this.CameraPitchOffset = CameraPitchOffset;
                this.HandPositionOffset = HandPositionOffset;
                this.MaxDistance = MaxDistance;
            }

            public SpawnThrowingCard()
            {
                this.CameraPositionOffset = new();
                this.HandPositionOffset = new();
            }

            string IReducerArgs.ReducerName => "SpawnThrowingCard";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SpawnThrowingCardFlags;
        public void SpawnThrowingCard(CallReducerFlags flags) => SpawnThrowingCardFlags = flags;
    }
}
