// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TestSmokeHandler(ReducerEventContext ctx);
        public event TestSmokeHandler? OnTestSmoke;

        public void TestSmoke()
        {
            conn.InternalCallReducer(new Reducer.TestSmoke(), this.SetCallReducerFlags.TestSmokeFlags);
        }

        public bool InvokeTestSmoke(ReducerEventContext ctx, Reducer.TestSmoke args)
        {
            if (OnTestSmoke == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTestSmoke(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TestSmoke : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "test_smoke";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TestSmokeFlags;
        public void TestSmoke(CallReducerFlags flags) => TestSmokeFlags = flags;
    }
}
