// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TryLeaveGameHandler(ReducerEventContext ctx);
        public event TryLeaveGameHandler? OnTryLeaveGame;

        public void TryLeaveGame()
        {
            conn.InternalCallReducer(new Reducer.TryLeaveGame(), this.SetCallReducerFlags.TryLeaveGameFlags);
        }

        public bool InvokeTryLeaveGame(ReducerEventContext ctx, Reducer.TryLeaveGame args)
        {
            if (OnTryLeaveGame == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTryLeaveGame(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TryLeaveGame : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "try_leave_game";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TryLeaveGameFlags;
        public void TryLeaveGame(CallReducerFlags flags) => TryLeaveGameFlags = flags;
    }
}
