// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GameHandle : RemoteTableHandle<EventContext, Game>
        {
            protected override string RemoteTableName => "game";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Game row) => row.Id;

                public IdUniqueIndex(GameHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class InProgressIndex : BTreeIndexBase<bool>
            {
                protected override bool GetKey(Game row) => row.InProgress;

                public InProgressIndex(GameHandle table) : base(table) { }
            }

            public readonly InProgressIndex InProgress;

            internal GameHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                InProgress = new(this);
            }

            protected override object GetPrimaryKey(Game row) => row.Id;
        }

        public readonly GameHandle Game;
    }
}
