// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GameTimersHandle : RemoteTableHandle<EventContext, GameTimersTimer>
        {
            protected override string RemoteTableName => "game_timers";

            public sealed class GameIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(GameTimersTimer row) => row.GameId;

                public GameIdUniqueIndex(GameTimersHandle table) : base(table) { }
            }

            public readonly GameIdUniqueIndex GameId;

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(GameTimersTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(GameTimersHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal GameTimersHandle(DbConnection conn) : base(conn)
            {
                GameId = new(this);
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(GameTimersTimer row) => row.ScheduledId;
        }

        public readonly GameTimersHandle GameTimers;
    }
}
