// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class HandleMagicianTimersTimerHandle : RemoteTableHandle<EventContext, HandleMagicianTimersTimer>
        {
            protected override string RemoteTableName => "handle_magician_timers_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(HandleMagicianTimersTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(HandleMagicianTimersTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal HandleMagicianTimersTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(HandleMagicianTimersTimer row) => row.ScheduledId;
        }

        public readonly HandleMagicianTimersTimerHandle HandleMagicianTimersTimer;
    }
}
