// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class HandleMagicianStatelessTimersTimerHandle : RemoteTableHandle<EventContext, HandleMagicianStatelessTimersTimer>
        {
            protected override string RemoteTableName => "handle_magician_stateless_timers_timer";

            public sealed class GameIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(HandleMagicianStatelessTimersTimer row) => row.GameId;

                public GameIdUniqueIndex(HandleMagicianStatelessTimersTimerHandle table) : base(table) { }
            }

            public readonly GameIdUniqueIndex GameId;

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(HandleMagicianStatelessTimersTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(HandleMagicianStatelessTimersTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal HandleMagicianStatelessTimersTimerHandle(DbConnection conn) : base(conn)
            {
                GameId = new(this);
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(HandleMagicianStatelessTimersTimer row) => row.ScheduledId;
        }

        public readonly HandleMagicianStatelessTimersTimerHandle HandleMagicianStatelessTimersTimer;
    }
}
