// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LoggedInPlayersHandle : RemoteTableHandle<EventContext, Player>
        {
            protected override string RemoteTableName => "logged_in_players";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Player row) => row.Id;

                public IdUniqueIndex(LoggedInPlayersHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Player row) => row.Identity;

                public IdentityUniqueIndex(LoggedInPlayersHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal LoggedInPlayersHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                Identity = new(this);
            }

            protected override object GetPrimaryKey(Player row) => row.Identity;
        }

        public readonly LoggedInPlayersHandle LoggedInPlayers;
    }
}
