// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MagicianHandle : RemoteTableHandle<EventContext, Magician>
        {
            protected override string RemoteTableName => "magician";

            public sealed class GameIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(Magician row) => row.GameId;

                public GameIdIndex(MagicianHandle table) : base(table) { }
            }

            public readonly GameIdIndex GameId;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Magician row) => row.Id;

                public IdUniqueIndex(MagicianHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Magician row) => row.Identity;

                public IdentityUniqueIndex(MagicianHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal MagicianHandle(DbConnection conn) : base(conn)
            {
                GameId = new(this);
                Id = new(this);
                Identity = new(this);
            }

            protected override object GetPrimaryKey(Magician row) => row.Identity;
        }

        public readonly MagicianHandle Magician;
    }
}
