// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MagicianEffectsHandle : RemoteTableHandle<EventContext, HandleMagicianEffectsTimer>
        {
            protected override string RemoteTableName => "magician_effects";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(HandleMagicianEffectsTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(MagicianEffectsHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal MagicianEffectsHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(HandleMagicianEffectsTimer row) => row.ScheduledId;
        }

        public readonly MagicianEffectsHandle MagicianEffects;
    }
}
