// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MatchHandle : RemoteTableHandle<EventContext, Match>
        {
            protected override string RemoteTableName => "match";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Match row) => row.Id;

                public IdUniqueIndex(MatchHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class StartedIndex : BTreeIndexBase<bool>
            {
                protected override bool GetKey(Match row) => row.InProgress;

                public StartedIndex(MatchHandle table) : base(table) { }
            }

            public readonly StartedIndex Started;

            internal MatchHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                Started = new(this);
            }

            protected override object GetPrimaryKey(Match row) => row.Id;
        }

        public readonly MatchHandle Match;
    }
}
