// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MoveAllMagiciansHandle : RemoteTableHandle<EventContext, MoveAllMagiciansTimer>
        {
            protected override string RemoteTableName => "move_all_magicians";

            public sealed class GameIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(MoveAllMagiciansTimer row) => row.GameId;

                public GameIdUniqueIndex(MoveAllMagiciansHandle table) : base(table) { }
            }

            public readonly GameIdUniqueIndex GameId;

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(MoveAllMagiciansTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(MoveAllMagiciansHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal MoveAllMagiciansHandle(DbConnection conn) : base(conn)
            {
                GameId = new(this);
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(MoveAllMagiciansTimer row) => row.ScheduledId;
        }

        public readonly MoveAllMagiciansHandle MoveAllMagicians;
    }
}
