// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MoveProjectilesAndCheckCollisionsHandle : RemoteTableHandle<EventContext, MoveProjectilesAndCheckCollisionsTimer>
        {
            protected override string RemoteTableName => "move_projectiles_and_check_collisions";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(MoveProjectilesAndCheckCollisionsTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(MoveProjectilesAndCheckCollisionsHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal MoveProjectilesAndCheckCollisionsHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(MoveProjectilesAndCheckCollisionsTimer row) => row.ScheduledId;
        }

        public readonly MoveProjectilesAndCheckCollisionsHandle MoveProjectilesAndCheckCollisions;
    }
}
