// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PingStatusHandle : RemoteTableHandle<EventContext, PingStatus>
        {
            protected override string RemoteTableName => "ping_status";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(PingStatus row) => row.Identity;

                public IdentityUniqueIndex(PingStatusHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal PingStatusHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(PingStatus row) => row.Identity;
        }

        public readonly PingStatusHandle PingStatus;
    }
}
