// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerEffectsTableTimerHandle : RemoteTableHandle<EventContext, PlayerEffectsTableTimer>
        {
            protected override string RemoteTableName => "player_effects_table_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerEffectsTableTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(PlayerEffectsTableTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal PlayerEffectsTableTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(PlayerEffectsTableTimer row) => row.ScheduledId;
        }

        public readonly PlayerEffectsTableTimerHandle PlayerEffectsTableTimer;
    }
}
