// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerEffectsHandle : RemoteTableHandle<EventContext, PlayerEffect>
        {
            protected override string RemoteTableName => "player_effects";

            public sealed class GameIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(PlayerEffect row) => row.GameId;

                public GameIdIndex(PlayerEffectsHandle table) : base(table) { }
            }

            public readonly GameIdIndex GameId;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerEffect row) => row.Id;

                public IdUniqueIndex(PlayerEffectsHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class SenderAndTypeIndex : BTreeIndexBase<(ulong SenderId, EffectType EffectType)>
            {
                protected override (ulong SenderId, EffectType EffectType) GetKey(PlayerEffect row) => (row.SenderId, row.EffectType);

                public SenderAndTypeIndex(PlayerEffectsHandle table) : base(table) { }
            }

            public readonly SenderAndTypeIndex SenderAndType;

            public sealed class SenderIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerEffect row) => row.SenderId;

                public SenderIdIndex(PlayerEffectsHandle table) : base(table) { }
            }

            public readonly SenderIdIndex SenderId;

            public sealed class TargetAndTypeIndex : BTreeIndexBase<(ulong TargetId, EffectType EffectType)>
            {
                protected override (ulong TargetId, EffectType EffectType) GetKey(PlayerEffect row) => (row.TargetId, row.EffectType);

                public TargetAndTypeIndex(PlayerEffectsHandle table) : base(table) { }
            }

            public readonly TargetAndTypeIndex TargetAndType;

            public sealed class TargetIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerEffect row) => row.TargetId;

                public TargetIdIndex(PlayerEffectsHandle table) : base(table) { }
            }

            public readonly TargetIdIndex TargetId;

            public sealed class TargetSenderAndTypeIndex : BTreeIndexBase<(ulong TargetId, ulong SenderId, EffectType EffectType)>
            {
                protected override (ulong TargetId, ulong SenderId, EffectType EffectType) GetKey(PlayerEffect row) => (row.TargetId, row.SenderId, row.EffectType);

                public TargetSenderAndTypeIndex(PlayerEffectsHandle table) : base(table) { }
            }

            public readonly TargetSenderAndTypeIndex TargetSenderAndType;

            internal PlayerEffectsHandle(DbConnection conn) : base(conn)
            {
                GameId = new(this);
                Id = new(this);
                SenderAndType = new(this);
                SenderId = new(this);
                TargetAndType = new(this);
                TargetId = new(this);
                TargetSenderAndType = new(this);
            }

            protected override object GetPrimaryKey(PlayerEffect row) => row.Id;
        }

        public readonly PlayerEffectsHandle PlayerEffects;
    }
}
