// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerEffectsHandle : RemoteTableHandle<EventContext, PlayerEffects>
        {
            protected override string RemoteTableName => "player_effects";

            public sealed class GameIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(PlayerEffects row) => row.GameId;

                public GameIdIndex(PlayerEffectsHandle table) : base(table) { }
            }

            public readonly GameIdIndex GameId;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerEffects row) => row.Id;

                public IdUniqueIndex(PlayerEffectsHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class TargetIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerEffects row) => row.TargetId;

                public TargetIdIndex(PlayerEffectsHandle table) : base(table) { }
            }

            public readonly TargetIdIndex TargetId;

            internal PlayerEffectsHandle(DbConnection conn) : base(conn)
            {
                GameId = new(this);
                Id = new(this);
                TargetId = new(this);
            }

            protected override object GetPrimaryKey(PlayerEffects row) => row.Id;
        }

        public readonly PlayerEffectsHandle PlayerEffects;
    }
}
